config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  root to: 'home#index'
  get '/all', to: 'home#user_list', as: 'all'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :exception

  before_action :sanitize_devise_params, if: :devise_controller?

  def sanitize_devise_params
    devise_parameter_sanitizer.permit(:sign_up, keys:[:prenom])
    devise_parameter_sanitizer.permit(:sign_up, keys:[:nom])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def user_list
    @user = User.all
  end

  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<% if user_signed_in? %>

     <h1> Bienvenu cher membre <br> Pour rejoindre notre site cliquez ici :<br>
     <%= link_to 'Super site encore plus privé ;)', all_path %></h1>


<% else %>

     <h1> Vous devez vous connecter pour rejoindre notre site </h1>

<% end %>

app/views/home/user_list.html.erb
<% if user_signed_in? %>
  <h1>Nos membres très privés</h1>

  <table>
    <thead>
      <tr>
        <th>Nom</th>
        <th>| Prénom</th>
        <th>| E-mail</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @user.each do |user| %>
        <tr>
          <td><%= user.nom %></td>
          <td>| &nbsp;  <%= user.prenom %></td>
          <td>| &nbsp; <%= user.email %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <% else %>

       <h1> On vous a dit de vous connecter XD ! </h1>

  <% end %>

<br>
<br>
<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Timetotest</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>

  </head>

  <body>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark navbar-fixed-top">
     <a class="navbar-brand" href="#">Site VIP très privé XD</a>
     <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
       <span class="navbar-toggler-icon"></span>
     </button>

     <div class="collapse navbar-collapse" id="navbarsExampleDefault">
       <ul class="navbar-nav mr-auto">
         <li class="nav-item active">
           <a class="nav-link" href="<%= root_path %>">Home <span class="sr-only">(current)</span></a>
         </li>

       </ul>
         <ul class="nav navbar-nav navbar-right">
           <% if user_signed_in? %>

              <li class="nav-item">
                <%= current_user.prenom %> &ensp;
              </li>

              <li class="nav-item">
                <%= link_to "Profil", edit_user_registration_path %> &ensp;
              </li>
              <li class="nav-item">
                <%= link_to "Log Out", destroy_user_session_path, method: :delete %>
              </li>

           <% else %>
              <li class="nav-item">
                <a class="nav-link" href="<%= new_user_session_path %>">Log in</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="<%= new_user_registration_path %>">Sign up</a>
              </li>
          <% end %>


       </ul>
     </div>
   </nav>
    <%= yield %>
  </body>
</html>